### ISSUE TITLE
Show systems' descriptions in Context and Landscape diagrams

### ISSUE THREAD

**Issue by igor-toporet** [Carbide-Software/Carbide-Support#5]
"Canonical" C4 models include descriptions in diagrams, which helps with comprehensibility. Do you plan to have them too in future versions? It would also be nice to have an ON/OFF switch to control this behavior.

### Expected behavior

https://c4model.com/img/bigbankplc-SystemContext.png

<img width="396" alt="image" src="https://user-images.githubusercontent.com/758320/180128115-03175805-adb8-44a6-bc3c-d66218f0405b.png">

### Actual behavior

<img width="610" alt="image" src="https://user-images.githubusercontent.com/758320/180129147-2f055a85-2792-450e-bd34-9f5cfba24006.png">

----

Thanks for the great product and for offering it free to alpha users!

----

P.S. The arrows also don't have any captions. But I guess it's worth a separate issue.

**Comment by andersme** [comment]
We have implemented this in the latest version. We tried putting the whole descriptions in the diagram, but thought they were distracting. We instead put a information button that you can hover over to see the description. Let us know what you think.
